services:
  db:
    image: postgis/postgis:16-3.4
    container_name: bus_tracker_db
    environment:
      POSTGRES_DB: bus_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bus_tracker_data:/var/lib/postgresql/data
    
volumes:
  bus_tracker_data:

# docker compose up -d